apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-cluster
  region: ap-south-1
  version: "1.29"
managedNodeGroups:
  - name: node-group-1
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
